#!/bin/sh
# generate and tests a trend distribution

# trap errors
set -e

# basic data
REV="`git describe $1 | sed -e s/^trend-//`"
DIST="trend-$REV"
HEAD="trend $REV"
CATALOG="
	AUTHORS THANKS.rst COPYING README.rst TODO.rst NEWS.rst trend.1
	src/Makefile src/trend.cc src/version.h src/defaults.hh src/color.cc
	src/color.hh src/rr.hh src/timer.hh src/gl.hh examples/imem
	examples/tstimes examples/mem examples/net examples/timeq
"

# check ancillary files
echo "1: checking files"
head -1 NEWS.rst | fgrep -s "$HEAD"
grep -q '\<TODO\>' README.rst || true

for file in $CATALOG
do
  test -f $file
done


# creating distribution
echo "2: creating distribution"
(
  cd src
  make distclean
  make dist
)
rm -rf "$DIST"
mkdir "$DIST"
tar -cf - $CATALOG | { cd "$DIST" && tar xf -; }
{ tar -cf - --owner 0 --group 0 "$DIST" || tar -cf - "$DIST"; } | \
	gzip -9 > "$DIST.tar.gz"
rm -rf "$DIST"


# check
echo "3: checking distribution"
gzip -dc "$DIST.tar.gz" | tar xf -
(
  cd "$DIST/src"
  pmake || make
  test -x trend
)
rm -rf "$DIST"


# ok
echo "= generated $DIST:"
gzip -dc "$DIST.tar.gz" | tar tvf -
