#!/bin/sh
# generate and tests a trend distribution

# basic data
LOG="`p4 filelog -m1 trend.cc`"
REV="`echo $LOG | sed -ne 's/.* \.\.\. #\([0-9]*\) .*/\1/p'`"
ISODATE="`echo $LOG | sed -ne 's/.* on \([0-9]*\)\/\([0-9]*\)\/\([0-9]*\) by .*/\3\/\2\/\1/p'`"
DATE="`echo $LOG | sed -ne 's/.* on \([0-9]*\)\/\([0-9]*\)\/\([0-9]*\) by .*/\1\2\3/p'`"
DIST="trend-$DATE"
HEAD=" to Rev #$REV $ISODATE"
CATALOG="
	Makefile
	imem tstimes mem net timeq
	trend.cc defaults.hh color.cc color.hh rr.hh timer.hh gl.hh
	AUTHORS COPYING README TODO NEWS trend.1
"


# trap errors
set -e


# check ancillary files
echo "1: checking files"
if [ "$1" != "-" ]
then
	head -1 NEWS | fgrep -s "$HEAD"
	grep -q '\<TODO\>' README || true
fi


# creating distribution
echo "2: creating distribution"
rm -rf "$DIST"
mkdir "$DIST"
cp -p $CATALOG "$DIST"
{ tar -cf - --owner 0 --group 0 "$DIST" || tar -cf - "$DIST"; } | \
	gzip -9 > "$DIST.tar.gz"
rm -rf "$DIST"


# check
echo "3: checking distribution"
gzip -dc "$DIST.tar.gz" | tar xf -
cd "$DIST"
pmake || make
test -x trend
cd ..
rm -rf "$DIST"


# ok
echo "= generated $DIST:"
gzip -dc "$DIST.tar.gz" | tar tvf -
