#!/bin/sh
# generate and tests a new debian trend package

# trap errors
set -e

# basic data
REV="`git describe $1 | sed -e s/^trend-//`"
DIST="trend-$REV"
HEAD="trend ($REV-"

# check matching version
head -1 debian/changelog | fgrep -s "$HEAD"

# generate the source package
./gendist "$@"

# working directory
rm -fr trend_*
tar xvzf "$DIST.tar.gz"
mv "$DIST.tar.gz" "trend_$REV.orig.tar.gz"
cp -r debian "$DIST"

# build the package
cd "$DIST"
unset CPP CC CXX CPPFLAGS CFLAGS CXXFLAGS FFLAGS LDFLAGS
dpkg-buildpackage -si -k153410EC

# remove aux. files
cd ..
rm -rf "$DIST"

# checks
lintian --show-overrides -IE --pedantic trend_$REV-*.changes
