#!/bin/sh
# generate and tests a trend distribution

# basic data
REV="`git describe | sed -e s/^trend-//`"
DIST="trend-$REV"
HEAD="trend $REV"
CATALOG="
	AUTHORS THANKS COPYING README TODO NEWS trend.1
	src/Makefile src/trend.cc src/version.h src/defaults.hh
	src/color.cc src/color.hh src/rr.hh src/timer.hh src/gl.hh
	examples/imem examples/tstimes examples/mem
	examples/net examples/timeq
"

# trap errors
set -e


# check ancillary files
echo "1: checking files"
if [ "$1" != "-" ]
then
	head -1 NEWS | fgrep -s "$HEAD"
	grep -q '\<TODO\>' README || true
fi


# creating distribution
echo "2: creating distribution"
(
  cd src
  make distclean
  make dist
)
rm -rf "$DIST"
mkdir "$DIST"
tar -cf - $CATALOG | { cd "$DIST" && tar xf -; }
{ tar -cf - --owner 0 --group 0 "$DIST" || tar -cf - "$DIST"; } | \
	gzip -9 > "$DIST.tar.gz"
rm -rf "$DIST"


# check
echo "3: checking distribution"
gzip -dc "$DIST.tar.gz" | tar xf -
(
  cd "$DIST/src"
  pmake || make
  test -x trend
)
rm -rf "$DIST"


# ok
echo "= generated $DIST:"
gzip -dc "$DIST.tar.gz" | tar tvf -
