#!/bin/sh
# generate and tests a new debian trend package

# trap errors
set -e

# basic data
REV="`git describe | sed -e s/^trend-//`"
HEAD="trend ($REV-"
DIST="trend-$REV"

# check matching version
if [ "$1" != "-" ]
then
	head -1 debian/changelog | fgrep -s "$HEAD"
	grep -q '\<TODO\>' README || true
fi

# generate the source package
./gendist "$@"

# working directory
rm -fr trend_*
tar xvzf "$DIST.tar.gz"
mv "$DIST.tar.gz" "trend_$REV.orig.tar.gz"
cp -r debian "$DIST"

# build the package
cd "$DIST"
unset CPP CXX CPPFLAGS CXXFLAGS LDFLAGS
dpkg-buildpackage -rfakeroot -us -uc

# remove aux. files
cd ..
rm -rf "$DIST"

# checks
lintian trend_$REV-*.dsc
lintian trend_$REV-*_*.deb

