#!/usr/bin/env perl
# network usage for trend

use strict;
use warnings;
use Time::HiRes "usleep";
$| = 1;

my $if = "eth0";
my $old = 0;

while()
{
  open FD, "/proc/net/dev" or die;
  while(<FD>)
  {
    my ($in, $out) = /^ *$if\:(\d+) +\d+ +\d+ +\d+ +\d+ +\d+ +\d+ +\d+ +(\d+)/;
    if($in && $out)
    {
      my $cnt = $in + $out;
      $old = $cnt if($old == 0);
      print(($cnt - $old) . "\n");
      
      $old = $cnt;
      last;
    }
  }
  close FD;

  usleep ($ARGV[0]? $ARGV[0]: 100000);
}

