#!/usr/bin/env perl
# network usage for trend

use strict;
use warnings;
use Time::HiRes "usleep";

# be sure to flush right away!
$| = 1;

# arguments
my $old = 0;
my $ms = ($ARGV[0]? $ARGV[0]: 1) * 100000;
my $if = ($ARGV[1]? $ARGV[1]: "eth0");

# main loop
while()
{
  open FD, "/proc/net/dev" or die;
  while(<FD>)
  {
    my ($ent, $in, $out) = /^\s*([^\s:]+):\s*(\d+)\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+(\d+)/;
    if($ent and $ent eq $if)
    {
      my $cnt = $in + $out;
      $old = $cnt if($old == 0);
      print(($cnt - $old) . "\n");
      
      $old = $cnt;
      last;
    }
  }
  close FD;

  usleep $ms;
}

